### PR TITLE
PRO-240: Use db.Continue and db.Break when calling Badger.Iterator

### PR DESCRIPTION
**Pull request by lithp**
Improve code readability by using more meaningful constant names in lieu of `true` and `false`.

### CODE REVIEW

**Comment by recmo** [comment]
I think this PR needs updating before it can be reviewed.

**Comment by lithp** [comment]
@recmo updated, this is ready for review now

**Review by b-tarczynski — CHANGES_REQUESTED** [review]
There is [one more place](https://github.com/worldcoin/hubble-commander/blob/master/testutils/iterate_index.go#L30) where we can replace false with db.Break.

What do you think to return `db.Continue, err` on error in IteratorFilter. It's weird to return continue even when we returning from that function?

**Comment by lithp** [comment]
closing stale PR

**Pull request closed without merging**
